### ISSUE TITLE
Archives header can be than 3 lines long

### ISSUE THREAD

**Issue by Rhahi** [mtgred/netrunner#8041]
Not a gameplay breaking issue.

## Problem:

![Image](https://github.com/user-attachments/assets/56386f4e-da10-480e-a9e3-bc92fbc2747f)
Note: characters are enlarged. This also happens to normal size characters.

Archives header can be more than 3 lines long. Whether this is a problem or not is subject to opinions.

## Suggestion for solution:

Given current HTML:

```html
<div class="header server-label darkbg">Archives (11 ↑ 0 ↓)</div>
```

To control the line break behavior easier, the text can be split into two <span>s, and insert <wbr> to indicate line break opportunity.
Then, disallow line break for each <span>.

```html
<div class="header server-label darkbg">
  <span>Archives </span>
  <wbr>
  <span>(11 ↑ 0 ↓)</span>
</div>
```

```css
/* .corp here is important to not disturb runner part of discard pile */
.corp-board .discard-container .header span {
  white-space: preserve nowrap;
}
```
